import type { LevelDefinition, Step } from './types'

export const levels: LevelDefinition[] = [
  {
    name: 'Lối thoát đầu tiên',
    hint: 'Có 1 Pressure Plate. Hãy tạo 1 Echo đứng lên plate để mở cửa.',
    maxEchoes: 1,
    minEchoToClear: 1,
    maxLoopLength: 18,
    map: [
      '###########',
      '#S..D...X.#',
      '#.###.###.#',
      '#.#.....#.#',
      '#.#.###.#.#',
      '#P#.....#.#',
      '###########',
    ],
  },
  {
    name: 'Cổng đôi',
    hint: 'Hai plate phải được giữ cùng lúc để mở cả cụm cửa.',
    maxEchoes: 2,
    minEchoToClear: 1,
    maxLoopLength: 20,
    map: ['#############', '#S..D..D..X.#', '#.###.###.#.#', '#P........P.#', '#############'],
  },
  {
    name: 'Phòng đồng bộ',
    hint: 'Ba plate, hai cửa. Dùng nhiều Echo và canh nhịp bằng lệnh chờ.',
    maxEchoes: 3,
    minEchoToClear: 2,
    maxLoopLength: 24,
    map: [
      '###############',
      '#S..D....D..X.#',
      '#.##.####.##..#',
      '#P..#....#..P.#',
      '#.##.####.##..#',
      '#.....P.......#',
      '###############',
    ],
  },
  {
    name: 'Ngã ba lệch pha',
    hint: 'Cần khóa 3 plate để mở đường cửa đôi đến cổng thoát.',
    maxEchoes: 3,
    minEchoToClear: 2,
    maxLoopLength: 28,
    map: [
      '#################',
      '#S..D......D..X.#',
      '#.##.#######.##.#',
      '#P..#...P...#..P#',
      '#.##.#######.##.#',
      '#...............#',
      '#################',
    ],
  },
  {
    name: 'Mê cung hồi âm',
    hint: '4 plate ở 4 nhịp khác nhau. Ưu tiên tạo script ngắn rồi canh đợi.',
    maxEchoes: 4,
    minEchoToClear: 3,
    maxLoopLength: 30,
    map: [
      '###################',
      '#S..D..#......D.X.#',
      '#.##.#.#.####.#.#.#',
      '#P...#...P..#...P.#',
      '#.###.#####.###.#.#',
      '#.....P...........#',
      '###################',
    ],
  },
  {
    name: 'Cánh cổng cuối',
    hint: 'Level cuối: giữ đồng thời 4 plate, sau đó thoát trước khi nhịp lệch.',
    maxEchoes: 4,
    minEchoToClear: 3,
    maxLoopLength: 34,
    map: [
      '#####################',
      '#S...D....#....D..X.#',
      '#.###.###.#.###.##..#',
      '#P..#...#...#...#P..#',
      '###.#.#.#####.#.###.#',
      '#P....#...P...#.....#',
      '#####################',
    ],
  },
]

export const movementKeyMap: Record<string, Step> = {
  ArrowUp: 'U',
  ArrowDown: 'D',
  ArrowLeft: 'L',
  ArrowRight: 'R',
  w: 'U',
  W: 'U',
  s: 'D',
  S: 'D',
  a: 'L',
  A: 'L',
  d: 'R',
  D: 'R',
  ' ': 'W',
}

export const stepLabelMap: Record<Step, string> = {
  U: '↑',
  D: '↓',
  L: '←',
  R: '→',
  W: '•',
}
