import type { LessonStep, PlanetDefinition, PlanetId, QuizQuestion } from './types'

export const AU_KM = 149_597_870.7
export const EARTH_YEAR_DAYS = 365.256
export const EARTH_DIAMETER_KM = 12_742
export const MAX_DISTANCE_AU = 30.07
export const DAY_IN_MS = 86_400_000

export const PLANETS: PlanetDefinition[] = [
  {
    id: 'mercury',
    name: 'Sao Thủy',
    englishName: 'Mercury',
    distanceAU: 0.39,
    orbitalPeriodDays: 87.97,
    diameterKm: 4_879,
    rotationLabel: '58.6 ngày Trái Đất',
    moons: 0,
    description: 'Hành tinh nhỏ nhất và gần Mặt Trời nhất, bề mặt đầy hố va chạm.',
    learningHint: 'Độ lệch tâm cao khiến quỹ đạo Sao Thủy hình elip rõ ràng nhất.',
    primaryColor: '#d8c8aa',
    secondaryColor: '#7f6d57',
    eccentricity: 0.2056,
    orbitalInclinationDeg: 7,
    axialTiltDeg: 0.03,
    perihelionArgDeg: 29,
    epochMeanAnomalyRad: 1.2,
    seasonOffsetDeg: 5,
  },
  {
    id: 'venus',
    name: 'Sao Kim',
    englishName: 'Venus',
    distanceAU: 0.72,
    orbitalPeriodDays: 224.7,
    diameterKm: 12_104,
    rotationLabel: '243 ngày (quay ngược chiều)',
    moons: 0,
    description: 'Hành tinh nóng nhất vì hiệu ứng nhà kính rất mạnh.',
    learningHint: 'Sao Kim quay ngược chiều nên chu kỳ ngày-đêm rất đặc biệt.',
    primaryColor: '#f0c68d',
    secondaryColor: '#aa6f3a',
    eccentricity: 0.0068,
    orbitalInclinationDeg: 3.39,
    axialTiltDeg: 177.4,
    perihelionArgDeg: 54,
    epochMeanAnomalyRad: 2.7,
    seasonOffsetDeg: 18,
  },
  {
    id: 'earth',
    name: 'Trái Đất',
    englishName: 'Earth',
    distanceAU: 1,
    orbitalPeriodDays: 365.256,
    diameterKm: 12_742,
    rotationLabel: '23 giờ 56 phút',
    moons: 1,
    description: 'Hành tinh duy nhất đã biết có sự sống và đại dương lỏng ổn định.',
    learningHint: 'Độ nghiêng trục 23.44 độ tạo ra bốn mùa rõ ràng ở các vùng ôn đới.',
    primaryColor: '#65b8ff',
    secondaryColor: '#2e6b8f',
    eccentricity: 0.0167,
    orbitalInclinationDeg: 0,
    axialTiltDeg: 23.44,
    perihelionArgDeg: 102,
    epochMeanAnomalyRad: 5.5,
    seasonOffsetDeg: 0,
  },
  {
    id: 'mars',
    name: 'Sao Hỏa',
    englishName: 'Mars',
    distanceAU: 1.52,
    orbitalPeriodDays: 686.98,
    diameterKm: 6_779,
    rotationLabel: '24 giờ 37 phút',
    moons: 2,
    description: 'Hành tinh đỏ với nhiều dấu tích của sông và hồ cổ đại.',
    learningHint: 'Sao Hỏa có mùa tương tự Trái Đất nhưng mỗi mùa dài hơn.',
    primaryColor: '#f4865a',
    secondaryColor: '#9c4930',
    eccentricity: 0.0934,
    orbitalInclinationDeg: 1.85,
    axialTiltDeg: 25.19,
    perihelionArgDeg: 286,
    epochMeanAnomalyRad: 0.2,
    seasonOffsetDeg: 48,
  },
  {
    id: 'jupiter',
    name: 'Sao Mộc',
    englishName: 'Jupiter',
    distanceAU: 5.2,
    orbitalPeriodDays: 4_332.59,
    diameterKm: 139_820,
    rotationLabel: '9 giờ 56 phút',
    moons: 95,
    description: 'Hành tinh lớn nhất hệ Mặt Trời, nổi bật với Vết Đỏ Lớn.',
    learningHint: 'Độ nghiêng trục nhỏ nên sự biến đổi mùa trên Sao Mộc không mạnh.',
    primaryColor: '#f3c58a',
    secondaryColor: '#9b6e44',
    eccentricity: 0.0489,
    orbitalInclinationDeg: 1.31,
    axialTiltDeg: 3.13,
    perihelionArgDeg: 273,
    epochMeanAnomalyRad: 3.6,
    seasonOffsetDeg: 92,
  },
  {
    id: 'saturn',
    name: 'Sao Thổ',
    englishName: 'Saturn',
    distanceAU: 9.58,
    orbitalPeriodDays: 10_759.22,
    diameterKm: 116_460,
    rotationLabel: '10 giờ 33 phút',
    moons: 146,
    description: 'Nổi bật với hệ vành đai băng-bụi rộng và sáng rõ.',
    learningHint: 'Độ nghiêng trục 26.7 độ làm độ sáng vành đai thay đổi theo mùa.',
    primaryColor: '#f1dfb1',
    secondaryColor: '#9b8658',
    eccentricity: 0.0565,
    orbitalInclinationDeg: 2.49,
    axialTiltDeg: 26.73,
    perihelionArgDeg: 339,
    epochMeanAnomalyRad: 4.4,
    seasonOffsetDeg: 140,
  },
  {
    id: 'uranus',
    name: 'Sao Thiên Vương',
    englishName: 'Uranus',
    distanceAU: 19.2,
    orbitalPeriodDays: 30_688.5,
    diameterKm: 50_724,
    rotationLabel: '17 giờ 14 phút (trục nghiêng mạnh)',
    moons: 28,
    description: 'Hành tinh băng với trục quay nghiêng gần nằm ngang.',
    learningHint: 'Trục nghiêng 97.77 độ khiến Uranus có mùa cực đoan và rất dài.',
    primaryColor: '#9be7e2',
    secondaryColor: '#4a8b8e',
    eccentricity: 0.0472,
    orbitalInclinationDeg: 0.77,
    axialTiltDeg: 97.77,
    perihelionArgDeg: 96,
    epochMeanAnomalyRad: 1.9,
    seasonOffsetDeg: 182,
  },
  {
    id: 'neptune',
    name: 'Sao Hải Vương',
    englishName: 'Neptune',
    distanceAU: 30.07,
    orbitalPeriodDays: 60_182,
    diameterKm: 49_244,
    rotationLabel: '16 giờ 6 phút',
    moons: 16,
    description: 'Hành tinh xa Mặt Trời nhất với tốc độ gió rất lớn.',
    learningHint: 'Một năm trên Sao Hải Vương kéo dài khoảng 165 năm Trái Đất.',
    primaryColor: '#77a2ff',
    secondaryColor: '#3553a2',
    eccentricity: 0.0086,
    orbitalInclinationDeg: 1.77,
    axialTiltDeg: 28.32,
    perihelionArgDeg: 273,
    epochMeanAnomalyRad: 0.8,
    seasonOffsetDeg: 230,
  },
]

export const PLANET_IDS: PlanetId[] = [
  'mercury',
  'venus',
  'earth',
  'mars',
  'jupiter',
  'saturn',
  'uranus',
  'neptune',
]

export const LESSON_STEPS: LessonStep[] = [
  {
    id: 'step-1',
    title: 'Quan sát quỹ đạo elip',
    objective: 'Hiểu độ lệch tâm ảnh hưởng hình dạng quỹ đạo.',
    instructions:
      'Áp dụng bước này rồi so sánh Sao Thủy với Trái Đất: Sao Thủy có quỹ đạo dẹt và méo rõ hơn.',
    hint: 'Tăng tốc độ thời gian để thấy nhanh sự khác nhau trong 2-3 chu kỳ.',
    focusPlanetId: 'mercury',
    recommendedSpeed: 48,
    emphasis: 'eccentricity',
  },
  {
    id: 'step-2',
    title: 'Độ nghiêng quỹ đạo',
    objective: 'Nhận biết các mặt phẳng quỹ đạo không trùng nhau tuyệt đối.',
    instructions:
      'Bật hiển thị độ nghiêng quỹ đạo và theo dõi Sao Thủy, Sao Kim, Sao Hỏa để thấy độ lệch mặt phẳng.',
    hint: 'Giá trị i (độ) càng lớn thì quỹ đạo càng lệch khỏi mặt phẳng hoàng đạo.',
    focusPlanetId: 'mars',
    recommendedSpeed: 36,
    emphasis: 'inclination',
  },
  {
    id: 'step-3',
    title: 'Trục nghiêng và bốn mùa',
    objective: 'Liên hệ độ nghiêng trục với mùa ở hai bán cầu.',
    instructions:
      'Chọn Trái Đất, bật trục nghiêng và mùa. Theo dõi dòng "độ lệch Mặt Trời" để thấy mùa thay đổi.',
    hint: 'Mùa Bắc Bán Cầu và Nam Bán Cầu luôn ngược nhau.',
    focusPlanetId: 'earth',
    recommendedSpeed: 32,
    emphasis: 'season',
  },
  {
    id: 'step-4',
    title: 'So sánh cực đoan',
    objective: 'So sánh năm ngắn-và-dài và mùa cực đoan.',
    instructions:
      'Chuyển sang Uranus và Neptune, quan sát tốc độ quỹ đạo và mùa dài rất lâu.',
    hint: 'Uranus có trục nghiêng gần nằm ngang nên mùa cực đoan hơn Trái Đất.',
    focusPlanetId: 'uranus',
    recommendedSpeed: 70,
    emphasis: 'comparison',
  },
]

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: 'q1',
    question: 'Hành tinh nào có độ lệch tâm quỹ đạo lớn nhất trong 8 hành tinh?',
    choices: [
      { id: 'a', label: 'Sao Kim' },
      { id: 'b', label: 'Sao Thủy' },
      { id: 'c', label: 'Sao Mộc' },
      { id: 'd', label: 'Sao Hải Vương' },
    ],
    correctChoiceId: 'b',
    explanation: 'Sao Thủy có độ lệch tâm xấp xỉ 0.2056, cao nhất trong các hành tinh.',
  },
  {
    id: 'q2',
    question: 'Yếu tố nào tạo ra bốn mùa rõ nhất trên Trái Đất?',
    choices: [
      { id: 'a', label: 'Khoảng cách đến Mặt Trời thay đổi mạnh' },
      { id: 'b', label: 'Độ nghiêng trục quay của Trái Đất' },
      { id: 'c', label: 'Số lượng vệ tinh của Trái Đất' },
      { id: 'd', label: 'Tốc độ quay quanh trục quá chậm' },
    ],
    correctChoiceId: 'b',
    explanation: 'Độ nghiêng trục quay (23.44 độ) mới là nguyên nhân chính tạo mùa trên Trái Đất.',
  },
  {
    id: 'q3',
    question: 'Phát biểu nào đúng về mùa ở hai bán cầu?',
    choices: [
      { id: 'a', label: 'Hai bán cầu luôn cùng một mùa' },
      { id: 'b', label: 'Bắc bán cầu chậm hơn Nam bán cầu 1 mùa' },
      { id: 'c', label: 'Hai bán cầu có mùa đối nhau' },
      { id: 'd', label: 'Chỉ có Bắc bán cầu mới có mùa' },
    ],
    correctChoiceId: 'c',
    explanation: 'Khi Bắc Bán Cầu là mùa hè thì Nam Bán Cầu là mùa đông, và ngược lại.',
  },
  {
    id: 'q4',
    question: 'Hành tinh nào có trục nghiêng cực lớn gần nằm ngang?',
    choices: [
      { id: 'a', label: 'Sao Hỏa' },
      { id: 'b', label: 'Sao Thổ' },
      { id: 'c', label: 'Sao Thiên Vương' },
      { id: 'd', label: 'Sao Hải Vương' },
    ],
    correctChoiceId: 'c',
    explanation: 'Sao Thiên Vương có độ nghiêng trục xấp xỉ 97.77 độ, gần như nằm ngang.',
  },
]
